version: '3'

services:
  wordpress:
    image: bitnami/wordpress:latest
    container_name: wordpress
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      WORDPRESS_DATABASE_HOST: mariadb
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_NAME: onetenplus
      WORDPRESS_DATABASE_USER: onetenplus
      WORDPRESS_DATABASE_PASSWORD: onetenplus2025
    volumes:
      - ./wordpress:/bitnami

  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: onetenplus
      MARIADB_USER: onetenplus
      MARIADB_PASSWORD: onetenplus2025
    volumes:
      - ./mariadb:/bitnami

volumes:
  wordpress_data:
    driver: local
  mariadb_data:
    driver: local